### PR TITLE
Gulp tasks

### PR DESCRIPTION
**Pull request by suchermon**
Can someone goes through this and see if you can run `gulp styleguide` after the setup?

### CODE REVIEW

**Comment by cmlizama** [comment]
Getting this error. I installed Jekyll, not sure if i have to link it in my bash profile or something?
screen shot 2017-07-27 at 12 45 52 pm

**Comment by localhuman** [comment]
i can take a look too

**Comment by cmlizama** [comment]
I'm gonna clear my npm modules and cache, see if that helps

**Comment by localhuman** [comment]
might be a node version thing, but i had to install autoprefixer to get gulp to work.  

also getting the same error as @cmlizama 

tried getting around it by global installing jekyll `npm install -g jekyll`, but that didn't work.  also tried reinstalling `child-process` (which seems to be throwing the error) but that also didn't work.

**Comment by localhuman** [comment]
also, this isn't on you @suchermon but the `/bin/setup` command also seems broken to me

**Comment by suchermon** [comment]
Looks like I forgot to add `autoprexfier` into package.json. That's one. I'm gonna see what I'm missing for the jekyll part.

**Comment by localhuman** [comment]
which version of node / npm are you running?

**Comment by localhuman** [comment]
👍

**Comment by suchermon** [comment]
Styleguide should be running now. If you have time, please help me test again. Thanks!

**Pull request merged**
